/**
 * Type generator for `@marianmeres/onix`.
 *
 * Reads the Kros Onix OpenAPI (Swagger 2.0) schema from `docs/V1.json` and
 * emits `src/types.gen.ts` — a type-only module with one `export interface` per
 * schema definition, carrying the schema's (Slovak) descriptions as JSDoc.
 *
 * This script is a DEV tool (not part of the published `exports`), so using
 * `Deno.*` here is fine — the portability rule applies to `src/` only.
 *
 * Run via: `deno task gen:types` (which also runs `deno fmt` on the output).
 *
 * @module
 */

const SCHEMA_PATH = "docs/V1.json";
const OUT_PATH = "src/types.gen.ts";

interface SchemaProp {
	type?: string;
	format?: string;
	$ref?: string;
	items?: SchemaProp;
	enum?: (string | number)[];
	description?: string;
	readOnly?: boolean;
}

interface SchemaDef {
	type?: string;
	description?: string;
	required?: string[];
	properties?: Record<string, SchemaProp>;
}

interface Swagger {
	definitions: Record<string, SchemaDef>;
}

/** The 3 `PagedResult_*` defs are replaced by the generic `PagedResult<T>` in types.ts. */
const SKIP_PREFIX = "PagedResult_";

const refName = (ref: string): string => ref.split("/").pop() ?? ref;

/** `DtoDocument_get` -> `DtoDocumentGet`; `Result` -> `Result`. */
function toInterfaceName(name: string): string {
	return name
		.split("_")
		.map((seg, i) => i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1))
		.join("");
}

const VALID_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const quoteKey = (
	key: string,
): string => (VALID_IDENT.test(key) ? key : JSON.stringify(key));

/** Maps a Swagger property to a TypeScript type expression. */
function tsType(p: SchemaProp): string {
	if (p.enum && p.enum.length) {
		const isString = p.type === "string" ||
			typeof p.enum[0] === "string";
		return p.enum
			.map((v) => (isString ? JSON.stringify(String(v)) : String(v)))
			.join(" | ");
	}
	if (p.type === "array") {
		const it = p.items ?? {};
		if (it.$ref) return `${toInterfaceName(refName(it.$ref))}[]`;
		return `${tsType(it)}[]`;
	}
	if (p.$ref) return toInterfaceName(refName(p.$ref));
	switch (p.type) {
		case "integer":
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		case "string":
			return "string"; // date-time / byte are also strings
		case "object":
			return "unknown"; // unschema'd value bag (e.g. CustomField.Value)
		default:
			return "unknown";
	}
}

/** Cleans a Slovak description and appends derived format/readonly tags. */
function jsdocLines(p: SchemaProp): string[] {
	const lines: string[] = [];
	if (p.description) {
		const cleaned = p.description
			.replace(/\r\n?/g, "\n")
			.replace(/<br\s*\/?>/gi, "")
			.split("\n")
			.map((l) => l.trimEnd());
		// drop leading/trailing empty lines
		while (cleaned.length && cleaned[0] === "") cleaned.shift();
		while (cleaned.length && cleaned[cleaned.length - 1] === "") cleaned.pop();
		lines.push(...cleaned);
	}
	if (p.format === "date-time") lines.push("@format date-time (ISO 8601 string)");
	if (p.format === "byte") lines.push("@format byte (base64-encoded string)");
	if (p.type === "integer" && p.format === "int64") {
		lines.push("@format int64 (may exceed JS Number.MAX_SAFE_INTEGER)");
	}
	if (p.readOnly) lines.push("@readonly");
	return lines;
}

function emitJsdoc(p: SchemaProp): string {
	const lines = jsdocLines(p);
	if (!lines.length) return "";
	if (lines.length === 1) return `\t/** ${lines[0]} */\n`;
	return `\t/**\n${lines.map((l) => `\t * ${l}`.trimEnd()).join("\n")}\n\t */\n`;
}

/** Doc comment for an interface — uses the def description if present. */
function emitInterfaceDoc(name: string, def: SchemaDef): string {
	if (def.description) {
		const lines = def.description
			.replace(/\r\n?/g, "\n")
			.replace(/<br\s*\/?>/gi, "")
			.split("\n")
			.map((l) => l.trimEnd())
			.filter((l, i, a) => l !== "" || (i > 0 && i < a.length - 1));
		if (lines.length === 1) return `/** ${lines[0]} */`;
		return `/**\n${lines.map((l) => ` * ${l}`.trimEnd()).join("\n")}\n */`;
	}
	return `/** Onix \`${name}\` DTO (generated from docs/V1.json). */`;
}

function main(): void {
	const schema = JSON.parse(Deno.readTextFileSync(SCHEMA_PATH)) as Swagger;
	const defs = schema.definitions ?? {};
	const names = Object.keys(defs).sort();

	const out: string[] = [];
	out.push(
		"// deno-lint-ignore-file",
		"// =============================================================================",
		"// AUTO-GENERATED by scripts/gen-types.ts from docs/V1.json — DO NOT EDIT.",
		"// Regenerate with: `deno task gen:types`",
		"// Friendly aliases, enums and the generic PagedResult<T> live in ./types.ts.",
		"// =============================================================================",
		"",
		"/**",
		" * Raw Kros Onix DTOs, generated 1:1 from the OpenAPI (Swagger 2.0) schema.",
		" * Field names are preserved verbatim (the exact API wire keys).",
		" *",
		" * @module",
		" */",
		"",
	);

	let skipped = 0;
	for (const name of names) {
		if (name.startsWith(SKIP_PREFIX)) {
			skipped++;
			continue;
		}
		const def = defs[name];
		const required = new Set(def.required ?? []);
		const props = def.properties ?? {};
		out.push(emitInterfaceDoc(name, def));
		out.push(`export interface ${toInterfaceName(name)} {`);
		for (const [propName, prop] of Object.entries(props)) {
			const doc = emitJsdoc(prop) || `\t/** \`${propName}\`. */\n`;
			out.push(doc.replace(/\n$/, ""));
			const optional = required.has(propName) ? "" : "?";
			out.push(`\t${quoteKey(propName)}${optional}: ${tsType(prop)};`);
		}
		out.push("}", "");
	}

	if (skipped) {
		out.push(
			`// NOTE: ${skipped} \`${SKIP_PREFIX}*\` definition(s) intentionally not generated —`,
			"// use the generic `PagedResult<T>` from ./types.ts instead.",
			"",
		);
	}

	Deno.writeTextFileSync(OUT_PATH, out.join("\n"));
	const generated = names.filter((n) => !n.startsWith(SKIP_PREFIX)).length;
	console.log(`Generated ${OUT_PATH}: ${generated} interfaces (${skipped} skipped).`);
}

main();
