// deno-lint-ignore-file
// =============================================================================
// AUTO-GENERATED by scripts/gen-types.ts from docs/V1.json — DO NOT EDIT.
// Regenerate with: `deno task gen:types`
// Friendly aliases, enums and the generic PagedResult<T> live in ./types.ts.
// =============================================================================

/**
 * Raw Kros Onix DTOs, generated 1:1 from the OpenAPI (Swagger 2.0) schema.
 * Field names are preserved verbatim (the exact API wire keys).
 *
 * @module
 */

/** Zakáznícke (vlastné) DB pole */
export interface CustomField {
	/** Názov */
	Name?: string;
	/** Hodnota v DB */
	Value?: unknown;
}

/** DTO pre nastavenie stavu konkrétnemu dokladu. */
export interface DocumentCurrentState {
	/**
	 * IdRecord dokladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	DocumentIdRecord?: number;
	/**
	 * IdRecord stavu dokladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	DocumentStateIdRecord?: number;
}

/** DTO pre nastavenie zákazníckych (vlastných) DB polí konkrétnemu dokladu. */
export interface DocumentCustomColumns {
	/**
	 * IdRecord dokladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	DocumentIdRecord?: number;
	/** Zakáznícke (vlastné) DB polia */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre zostatky na sklade. */
export interface DtoBalance {
	/**
	 * ID skladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockId?: number;
	/** Názov skladu */
	StockName?: string;
	/**
	 * ID skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItemId?: number;
	/** Hodnota vlastnosti dávky 1 */
	PropertyText1?: string;
	/** Hodnota vlastnosti dávky 2 */
	PropertyText2?: string;
	/** Hodnota vlastnosti dávky 3 */
	PropertyText3?: string;
	/** Hodnota vlastnosti dávky 4 */
	PropertyText4?: string;
	/** Hodnota vlastnosti dávky 5 */
	PropertyText5?: string;
	/** Hodnota vlastnosti dávky 6 */
	PropertyText6?: string;
	/**
	 * ID vlastnosti dávky 1
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId1?: number;
	/**
	 * ID vlastnosti dávky 2
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId2?: number;
	/**
	 * ID vlastnosti dávky 3
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId3?: number;
	/**
	 * ID vlastnosti dávky 4
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId4?: number;
	/**
	 * ID vlastnosti dávky 5
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId5?: number;
	/**
	 * ID vlastnosti dávky 6
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId6?: number;
	/** Zostatok */
	Balance?: number;
	/** Výrobné číslo */
	SerialNumber?: string;
	/**
	 * Dátum výroby
	 * @format date-time (ISO 8601 string)
	 */
	DateManufacture?: string;
	/**
	 * Záručná doba od dodávateľa
	 * @format date-time (ISO 8601 string)
	 */
	DateExpiration?: string;
	/**
	 * Záručná doba pre odberateľa
	 * @format date-time (ISO 8601 string)
	 */
	DateExpirationForBuyer?: string;
}

/** Onix `DtoBatchProperties` DTO (generated from docs/V1.json). */
export interface DtoBatchProperties {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov vlastnosti. */
	Name?: string;
}

/** Onix `DtoBatchPropertyValues` DTO (generated from docs/V1.json). */
export interface DtoBatchPropertyValues {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov hodnoty konkrétnej vlastnosti. */
	Name?: string;
}

/** DTO trieda pre katalogové cenníky */
export interface DtoCatalogPricingLists {
	/**
	 * ID skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItem_IdRecord?: number;
	/** Číslo skladovej karty */
	StockItem_Ns_Number?: string;
	/**
	 * Typ skladovej karty.
	 * 1 - Skladová karta
	 * 2 - Služba
	 * 6 - Zariadenie
	 */
	StockItem_Type?: number;
	/**
	 * ID skladu
	 * Má význam pre cenu so spôsobom výpočtu: 3 - Skladová cena + marža.
	 * Pre ceny s iným spôsobom výpočtu nie je k dispozícii.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Stock_IdRecord?: number;
	/**
	 * Kód skladu
	 * Má význam pre cenu so spôsobom výpočtu: 3 - Skladová cena + marža.
	 * Pre ceny s iným spôsobom výpočtu nie je k dispozícii.
	 */
	Stock_Code?: string;
	/** Cena bez DPH */
	Price?: number;
	/** Cena s DPH */
	Price_Vat?: number;
	/**
	 * Spôsob výpočtu ceny
	 * 1 - Fixná cena
	 * 2 - Manažérska cena + marža
	 * 3 - Skladová cena + marža
	 * 4 - Cena z iného cenníka - zľava
	 */
	CalculationType?: number;
	/**
	 * Časová pečiatka
	 * Má význam pre cenu so spôsobom výpočtu: 3 - Skladová cena + marža.
	 * Pre ceny s iným spôsobom výpočtu nie je k dispozícii.
	 * @format date-time (ISO 8601 string)
	 */
	Timestamp?: string;
}

/** DTO trieda pre obálku prílohy dokladu. */
export interface DtoDocumentEnclosure {
	/**
	 * ID záznamu. Používa sa ako parameter pre načítanie prílohy, pre endpoint /api/v1/enclosures
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov prílohy */
	Name?: string;
	/** Popis prílohy */
	Description?: string;
	/** Prípona súboru prílohy */
	Extension?: string;
}

/** DTO trieda pre položku dokladu. */
export interface DtoDocumentItemGet {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov skladovej karty, služby, voľnej položky. */
	Stock_Items_Name?: string;
	/** Názov skladu. */
	Stock_Name?: string;
	/**
	 * PLU.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Plu?: number;
	/**
	 * Príznak, či je skladová karta skladačka.
	 * -1 - Je skladačka.
	 * 0 - Nie je skladačka.
	 */
	Is_Composite?: number;
	/** Príznak, či daná položka je podpoložka skladačky. */
	Is_Sub_Item?: boolean;
	/**
	 * Dátum výroby.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Manufacture?: string;
	/**
	 * Záručná doba od dodávateľa .
	 * @format date-time (ISO 8601 string)
	 */
	Date_Expiration?: string;
	/** Výrobné číslo / šarža. */
	Serial_Number?: string;
	/** Vlastnosti. */
	Properties_Text?: string;
	/** Množstvo. */
	User_Amount?: number;
	/** Popis. */
	Description?: string;
	/** Jednotková skladová cena výdaja. */
	Price_Issued_Stock?: number;
	/**
	 * Záručná doba pre odberateľa.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Expiration_For_Buyer?: string;
	/** Skladová cena spolu. */
	Price_Issued_Stock_Sum?: number;
	/** Manažérska cena spolu. */
	Price_Manager_Sum?: number;
	/** Vlastnosť 1 - názov. */
	Value_Name_1?: string;
	/** Vlastnosť 2 - názov. */
	Value_Name_2?: string;
	/** Vlastnosť 3 - názov. */
	Value_Name_3?: string;
	/** Vlastnosť 4 - názov. */
	Value_Name_4?: string;
	/** Vlastnosť 5 - názov. */
	Value_Name_5?: string;
	/** Vlastnosť 6 - názov. */
	Value_Name_6?: string;
	/** Vlastnosť 1 - názov - presun v rámci jedného skladu. */
	Value_Transfer_Name_1?: string;
	/** Vlastnosť 2 - názov - presun v rámci jedného skladu. */
	Value_Transfer_Name_2?: string;
	/** Vlastnosť 3 - názov - presun v rámci jedného skladu. */
	Value_Transfer_Name_3?: string;
	/** Vlastnosť 4 - názov - presun v rámci jedného skladu. */
	Value_Transfer_Name_4?: string;
	/** Vlastnosť 5 - názov - presun v rámci jedného skladu. */
	Value_Transfer_Name_5?: string;
	/** Vlastnosť 6 - názov - presun v rámci jedného skladu. */
	Value_Transfer_Name_6?: string;
	/**
	 * Typ položky.
	 * 0 - Nedefinované
	 * 1 - Skladová karta
	 * 2 - Služba
	 * 5 - Voľná položka
	 * 6 - Zariadenie
	 */
	Item_Type?: 0 | 1 | 2 | 5 | 6;
	/** Bitové pole príznakov uzamknutia cien a zliav. */
	Price_Locking_Flags?: number;
	/**
	 * Typ zaokrúhlenia jednotkovej ceny po zľave.
	 * 0 - Nedefinované
	 * 1 - Prirodzene
	 * 2 - Nahor
	 * 3 - Nadol
	 * 4 - Nezaokrúhľovať
	 */
	Unit_Price_Rounding_Type?: 0 | 1 | 2 | 3 | 4;
	/**
	 * Zaokrúhlenie jednotkovej ceny po zľave.
	 * 0 - Nedefinované,
	 * 1 - 0.0001,
	 * 2 - 0.001,
	 * 3 - 0.01,
	 * 4 - 0,1.
	 * 5 - 0.5,
	 * 6 - 1,
	 * 7 - 5,
	 * 8 - 10,
	 * 9 - 50.
	 * 10 - 100,
	 * 11 - 500,
	 * 12 - 1000,
	 * 13 - 0.00001,
	 * 14 - 0.000001.
	 * 15 - 0.0000001.
	 * 16 - 0.0000001.
	 * 17 - 0.05.
	 */
	Unit_Price_Rounding_Number?:
		| 0
		| 1
		| 2
		| 3
		| 17
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 13
		| 14
		| 15
		| 16;
	/**
	 * Zaokrúhlenie sumy spolu.
	 * 0 - Nedefinované,
	 * 1 - Prirodzene,
	 * 2 - Nahor,
	 * 3 - Nadol,
	 * 4 - Nezaokrúhľovať.
	 */
	Sum_Rounding_Type?: 0 | 1 | 2 | 3 | 4;
	/**
	 * Typ zaokrúhlenia sumy spolu.
	 * 0 - Nedefinované,
	 * 1 - 0.0001,
	 * 2 - 0.001,
	 * 3 - 0.01,
	 * 4 - 0,1.
	 * 5 - 0.5,
	 * 6 - 1,
	 * 7 - 5,
	 * 8 - 10,
	 * 9 - 50.
	 * 10 - 100,
	 * 11 - 500,
	 * 12 - 1000,
	 * 13 - 0.00001,
	 * 14 - 0.000001.
	 * 15 - 0.0000001.
	 * 16 - 0.0000001.
	 * 17 - 0.05.
	 */
	Sum_Rounding_Number?:
		| 0
		| 1
		| 2
		| 3
		| 17
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 13
		| 14
		| 15
		| 16;
	/** Jednotkové množstvo položky skladačky. */
	Amount_Unit?: number;
	/** Merná jednotka. */
	Measure_Unit?: string;
	/** Koeficient prepočtu vybraného balenia k hlavnému baleniu. */
	Stock_Items_Mu_Coefficient?: number;
	/**
	 * Identifikátor prepojených položiek.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Linked_Item?: number;
	/**
	 * Identifikátor zdrojového dokladu, z ktorého pochádza položka.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Source_Document?: number;
	/**
	 * Obal je povinný.
	 * -1 - Áno,
	 * 0 - Nie.
	 */
	Cover_Is_Compulsory?: number;
	/** Zľava za doklad bez DPH. */
	Doc_Discount_Lc?: number;
	/**
	 * Dátum rezervácie na sklade.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Reservation?: string;
	/** Rezervované množstvo. */
	Reservated_Amount?: number;
	/** Zľava za doklad s DPH. */
	Doc_Discount_Vat_Lc?: number;
	/** Strana MÁ DAŤ syntetika. */
	Account_Md_Syn?: string;
	/** Strana MÁ DAŤ analytika. */
	Account_Md_Anl?: string;
	/** Strana DAL syntetika. */
	Account_Dal_Syn?: string;
	/** Strana DAL analytika. */
	Account_Dal_Anl?: string;
	/** Intrastat - kód kombinovanej nomenklatúry. */
	Ist_Code?: string;
	/** Intrastat - kód KG. */
	Ist_Weight?: number;
	/** Intrastat - DMJ. */
	Ist_Dmj?: number;
	/** Intrastat - Opis tovaru. */
	Ist_Description?: string;
	/** Číslo skladovej karty, služby, voľnej položky. */
	Stock_Items_Ns_Number?: string;
	/** Kód skladu. */
	Stock_Code?: string;
	/** EAN skladu. */
	Stock_Ean?: string;
	/** Interné rozúčtovanie 1 - názov. */
	Ia_Name_1?: string;
	/** Interné rozúčtovanie 2 - názov. */
	Ia_Name_2?: string;
	/** Interné rozúčtovanie 3 - názov. */
	Ia_Name_3?: string;
	/** Interné rozúčtovanie 4 - názov. */
	Ia_Name_4?: string;
	/** Interné rozúčtovanie 5 - názov. */
	Ia_Name_5?: string;
	/** Interné rozúčtovanie 6 - názov. */
	Ia_Name_6?: string;
	/** Suma odpočítanej čiastky na riadnych faktúrach. */
	Deducted_Invoices?: number;
	/** Suma odpočítanej DPH . */
	Deducted_Vat?: number;
	/** Interné rozúčtovanie 1 - kód. */
	Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - kód. */
	Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - kód. */
	Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - kód. */
	Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - kód. */
	Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - kód. */
	Ia_Code_6?: string;
	/** Vlastný názov položky. */
	Item_Name?: string;
	/** Jednotková cena bez DPH. */
	Unit_Price_Base?: number;
	/** Jednotková cena s DPH. */
	Unit_Price_Base_Vat?: number;
	/** Zľava bez DPH v percentách. */
	Unit_Discount_Percent?: number;
	/** Zľava bez DPH v mene dokladu. */
	Unit_Discount?: number;
	/** Zľava s DPH v mene dokladu. */
	Unit_Discount_Vat?: number;
	/** Cena po zľave bez DPH. */
	Unit_Price?: number;
	/** Cena po zľave s DPH. */
	Unit_Price_Vat?: number;
	/** Spolu. */
	Sum?: number;
	/** Spolu s DPH. */
	Sum_Vat?: number;
	/** Manažérska jednotková cena. */
	Price_Manager?: number;
	/** Poradie položky v doklade. */
	Ordinal?: number;
	/** EAN kód pre hlavnú mernú jednotku. */
	Default_Measure_Ean_Code?: string;
	/** Jednotková cena po zľave v legislatívnej mene. */
	Unit_Price_Lc?: number;
	/** Jednotková cena po zľave s DPH v legislatívnej mene. */
	Unit_Price_Vat_Lc?: number;
	/** Jednotková cena pred zľavou v legislatívnej mene. */
	Unit_Price_Base_Lc?: number;
	/** Jednotková cena pred zľavou s DPH v legislatívnej mene. */
	Unit_Price_Base_Vat_Lc?: number;
	/** Skutočný účtovný zostatok */
	Real_Accounting_Balance?: number;
	/**
	 * Id skladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Stocks?: number;
	/**
	 * Id skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Stock_Items?: number;
	/** Jednotková hmotnosť položky (kg) */
	Stock_Item_Weight?: number;
	/**
	 * Príznak, či položka vstupuje do skladových pohybov.
	 * -1 - Vstupuje.
	 * 0 - Nevstupuje.
	 */
	Pv_Accept?: number;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre položku dokladu. */
export interface DtoDocumentItemPost {
	/**
	 * Externý identifikátor slúži na komunikáciu cez API.
	 * Identifikátor bude vrátený v odpovedi na request, aby ste dokázali identifikovať ku ktorému záznamu patria odpovede poslané ako response.
	 * Hodnota sa neukladá, ale mala by byť jedinečná.
	 */
	RecordExternalIdentificator: string;
	/** Názov skladovej karty, služby, voľnej položky. */
	Stock_Items_Name?: string;
	/** Názov skladu. */
	Stock_Name?: string;
	/**
	 * PLU.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Plu?: number;
	/**
	 * Dátum výroby.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Manufacture?: string;
	/**
	 * Záručná doba od dodávateľa .
	 * @format date-time (ISO 8601 string)
	 */
	Date_Expiration?: string;
	/** Výrobné číslo / šarža. */
	Serial_Number?: string;
	/** Množstvo. */
	User_Amount?: number;
	/** Popis. */
	Description?: string;
	/**
	 * Záručná doba pre odberateľa.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Expiration_For_Buyer?: string;
	/** Vlastnosť 1 - názov. */
	Value_Name_1?: string;
	/** Vlastnosť 2 - názov. */
	Value_Name_2?: string;
	/** Vlastnosť 3 - názov. */
	Value_Name_3?: string;
	/** Vlastnosť 4 - názov. */
	Value_Name_4?: string;
	/** Vlastnosť 5 - názov. */
	Value_Name_5?: string;
	/** Vlastnosť 6 - názov. */
	Value_Name_6?: string;
	/**
	 * Typ položky.
	 * 0 - Nedefinované
	 * 1 - Skladová karta
	 * 2 - Služba
	 * 5 - Voľná položka
	 * 6 - Zariadenie
	 */
	Item_Type?: 0 | 1 | 2 | 5 | 6;
	/**
	 * Typ zaokrúhlenia jednotkovej ceny po zľave.
	 * 0 - Nedefinované
	 * 1 - Prirodzene
	 * 2 - Nahor
	 * 3 - Nadol
	 * 4 - Nezaokrúhľovať
	 */
	Unit_Price_Rounding_Type?: 0 | 1 | 2 | 3 | 4;
	/**
	 * Zaokrúhlenie jednotkovej ceny po zľave.
	 * 0 - Nedefinované,
	 * 1 - 0.0001,
	 * 2 - 0.001,
	 * 3 - 0.01,
	 * 4 - 0,1.
	 * 5 - 0.5,
	 * 6 - 1,
	 * 7 - 5,
	 * 8 - 10,
	 * 9 - 50.
	 * 10 - 100,
	 * 11 - 500,
	 * 12 - 1000,
	 * 13 - 0.00001,
	 * 14 - 0.000001.
	 * 15 - 0.0000001.
	 * 16 - 0.0000001.
	 * 17 - 0.05.
	 */
	Unit_Price_Rounding_Number?:
		| 0
		| 1
		| 2
		| 3
		| 17
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 13
		| 14
		| 15
		| 16;
	/**
	 * Zaokrúhlenie sumy spolu.
	 * 0 - Nedefinované,
	 * 1 - Prirodzene,
	 * 2 - Nahor,
	 * 3 - Nadol,
	 * 4 - Nezaokrúhľovať.
	 */
	Sum_Rounding_Type?: 0 | 1 | 2 | 3 | 4;
	/**
	 * Typ zaokrúhlenia sumy spolu.
	 * 0 - Nedefinované,
	 * 1 - 0.0001,
	 * 2 - 0.001,
	 * 3 - 0.01,
	 * 4 - 0,1.
	 * 5 - 0.5,
	 * 6 - 1,
	 * 7 - 5,
	 * 8 - 10,
	 * 9 - 50.
	 * 10 - 100,
	 * 11 - 500,
	 * 12 - 1000,
	 * 13 - 0.00001,
	 * 14 - 0.000001.
	 * 15 - 0.0000001.
	 * 16 - 0.0000001.
	 * 17 - 0.05.
	 */
	Sum_Rounding_Number?:
		| 0
		| 1
		| 2
		| 3
		| 17
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 13
		| 14
		| 15
		| 16;
	/** Merná jednotka. */
	Measure_Unit?: string;
	/**
	 * Dátum rezervácie na sklade.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Reservation?: string;
	/** Rezervované množstvo. */
	Reservated_Amount?: number;
	/** Kód skladovej karty. */
	Stock_Item_Code?: string;
	/** Typ produktového kódu. */
	Product_Code_Type?: string;
	/** Strana MÁ DAŤ syntetika. */
	Account_Md_Syn?: string;
	/** Strana MÁ DAŤ analytika. */
	Account_Md_Anl?: string;
	/** Strana DAL syntetika. */
	Account_Dal_Syn?: string;
	/** Strana DAL analytika. */
	Account_Dal_Anl?: string;
	/** Intrastat - kód kombinovanej nomenklatúry. */
	Ist_Code?: string;
	/** Číslo skladovej karty, služby, voľnej položky. */
	Stock_Items_Ns_Number?: string;
	/** Kód skladu. */
	Stock_Code?: string;
	/** EAN skladu. */
	Stock_Ean?: string;
	/** Interné rozúčtovanie 1 - názov. */
	Ia_Name_1?: string;
	/** Interné rozúčtovanie 2 - názov. */
	Ia_Name_2?: string;
	/** Interné rozúčtovanie 3 - názov. */
	Ia_Name_3?: string;
	/** Interné rozúčtovanie 4 - názov. */
	Ia_Name_4?: string;
	/** Interné rozúčtovanie 5 - názov. */
	Ia_Name_5?: string;
	/** Interné rozúčtovanie 6 - názov. */
	Ia_Name_6?: string;
	/** Interné rozúčtovanie 1 - kód. */
	Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - kód. */
	Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - kód. */
	Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - kód. */
	Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - kód. */
	Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - kód. */
	Ia_Code_6?: string;
	/** Interné rozúčtovanie 1 - guid ext. */
	Ia_GuidExt_1?: string;
	/** Interné rozúčtovanie 2 - guid ext. */
	Ia_GuidExt_2?: string;
	/** Interné rozúčtovanie 3 - guid ext. */
	Ia_GuidExt_3?: string;
	/** Interné rozúčtovanie 4 - guid ext. */
	Ia_GuidExt_4?: string;
	/** Interné rozúčtovanie 5 - guid ext. */
	Ia_GuidExt_5?: string;
	/** Interné rozúčtovanie 6 - guid ext. */
	Ia_GuidExt_6?: string;
	/** Vlastný názov položky. */
	Item_Name?: string;
	/** Jednotková cena bez DPH. */
	Unit_Price_Base?: number;
	/** Jednotková cena s DPH. */
	Unit_Price_Base_Vat?: number;
	/** Zľava bez DPH v percentách. */
	Unit_Discount_Percent?: number;
	/** Zľava bez DPH v mene dokladu. */
	Unit_Discount?: number;
	/** Zľava s DPH v mene dokladu. */
	Unit_Discount_Vat?: number;
	/** Cena po zľave bez DPH. */
	Unit_Price?: number;
	/** Cena po zľave s DPH. */
	Unit_Price_Vat?: number;
	/** Spolu. */
	Sum?: number;
	/** Spolu s DPH. */
	Sum_Vat?: number;
	/** Manažérska jednotková cena. */
	Price_Manager?: number;
	/**
	 * Sadzba DPH – môže obsahovať hodnoty:
	 * Do 31.12.2024: 20, 10, 0, N, P
	 * Od 1.1.2025: 23, 19, 5, 0, N, P
	 */
	Vat_Rate_SysCode?: string;
	/** Skutočný účtovný zostatok */
	Real_Accounting_Balance?: number;
	/** Jednotková hmotnosť položky (kg) */
	Stock_Item_Weight?: number;
	/** Číslo partnera - dodávateľa. Použije sa pre priradenie dodávateľského cenníka podľa partnera. */
	Supplier_Code?: string;
	/** Kód karty u dodávateľa. Nastaví sa karte iba pri jej založení počas importu. */
	Supplier_Stock_Item_Code?: string;
	/** Kód dodávateľského cenníka. Nastaví sa karte iba pri jej založení počas importu. */
	Price_Catalog_Code?: string;
	/** Názov karty u dodávateľa. Nastaví sa karte iba pri jej založení počas importu. */
	Supplier_Stock_Item_Name?: string;
	/** Merná jednotka u dodávateľa. Nastaví sa karte iba pri jej založení počas importu. */
	Supplier_Measure_Unit?: string;
	/** Kód evidencie. */
	Stock_Items_Ns_Evid_Code?: string;
	/** Kód číselného radu. */
	Stock_Items_Ns_Code?: string;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre stav dokladu. */
export interface DtoDocumentState {
	/**
	 * IdRecord stavu dokladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov stavu dokladu */
	Name?: string;
	/** Či je stav nastavený Onixom automticky */
	IsAutomaticState?: boolean;
}

/** DTO trieda pre typ dokladu. */
export interface DtoDocumentType {
	/**
	 * Id typu dokladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id?: number;
	/** Názov typu dokladu */
	Name?: string;
	/** Názov obchodného cyklu pod ktorý doklad patrí */
	BussinesCycleName?: string;
}

/** DTO trieda pre doklad. */
export interface DtoDocumentGet {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Poznámka. */
	Doc_Description?: string;
	/** Úvodný text. */
	Introduction_Text?: string;
	/** Záverečný text. */
	Final_Text?: string;
	/** Dodacie a platobné podmienky. */
	Delivery_Text?: string;
	/** Predmet. */
	Subject?: string;
	/**
	 * Dátum vyhotovenia dokladu.
	 * Rok dátumu slúži ako párovacie kritérium dokladu. Ak dátum nie je zadaný, pri párovaní sa ignoruje a doklad sa hľadá medzi všetkými dokladmi.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Document?: string;
	/**
	 * Dátum prijatia.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Admission?: string;
	/**
	 * Dátum splatnosti.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Due?: string;
	/**
	 * Dátum vzniku daňovej povinnosti.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Chargebility_Date?: string;
	/**
	 * Dátum pre sadzby DPH.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Vatrate?: string;
	/**
	 * Dátum a čas výdaja zo skladu.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Release?: string;
	/**
	 * Dátum predpokladanej realizácie.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Exp_Realization?: string;
	/**
	 * Dátum skutočnej realizácie.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Realization?: string;
	/**
	 * Dátum dodania.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Delivery_Date?: string;
	/**
	 * Dátum a čas príjmu na sklad.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Receive?: string;
	/**
	 * Dátum platnosti dokladu.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Validity?: string;
	/**
	 * Dátum rezervácie.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Reservation_Doc?: string;
	/**
	 * História - dátum zmeny dokladu.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Changed?: string;
	/** Spôsob dopravy. */
	Transport_Type?: string;
	/** Forma úhrady. */
	Payment_Type?: string;
	/**
	 * Kurz meny dokladu.
	 * Pri editácii dokladu ho nie je možné zmeniť.
	 */
	Exchange_Rate?: number;
	/** Suma v mene dokladu. */
	Sum?: number;
	/** Suma dokladu v legislatívnej mene. */
	Sum_Lc?: number;
	/** Suma s DPH v mene dokladu. */
	Sum_Vat?: number;
	/** Suma s DPH v legislatívnej mene. */
	Sum_Vat_Lc?: number;
	/** Zostatok k úhrade s DPH v mene dokladu. */
	Payment_Remaining?: number;
	/** Suma úhrady s DPH v mene dokladu. */
	Payment_Status?: number;
	/** Suma úhrady s DPH v legislatívnej mene. */
	Payment_Status_Lc?: number;
	/**
	 * Mena dokladu.
	 * Pri editácii dokladu ju nie je možné zmeniť.
	 */
	Curr?: string;
	/** Cieľový sklad názov - prevodka. */
	Stock_Transfer_Name?: string;
	/** Kód číselného radu. Ak je zadaný tak slúži ako párovacie kritérium. */
	Ns_Code?: string;
	/** Kód evidencie. Ak je zadaný tak slúži ako párovacie kritérium. */
	Ns_Evid_Code?: string;
	/** Číslo dokladu. Slúži ako párovacie kritérium dokladu. */
	Ns_Number?: string;
	/** Číslo účtu (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Account_Number?: string;
	/** Variabilný symbol. */
	Variable_Symbol?: string;
	/** Špecifický symbol. */
	Specific_Symbol?: string;
	/** Kód banky (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Bank_Code?: string;
	/** Konštantný symbol. */
	Constant_Symbol?: string;
	/** Externé číslo dokladu. */
	External_Number?: string;
	/** Číslo účtu vo formáte IBAN (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Iban?: string;
	/** SWIFT kód banky (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Swift?: string;
	/**
	 * Spôsob výpočtu celkovej sumy dokladu.
	 * 1 - Bez DPH,
	 * 2 - S DPH.
	 */
	Total_Price_Calculation?: 1 | 2;
	/** Stav dokladu. */
	Document_State?: string;
	/** Číslo partnera. */
	Ns_Number_Partner?: string;
	/** EAN partnera. */
	Partner_Ean?: string;
	/** IČO partnera. */
	Partner_Reg?: string;
	/** DIČ partnera. */
	Partner_Tax?: string;
	/** Partner - IČ DPH. */
	Partner_Vat_No?: string;
	/** Partner - stredisko. */
	Partner_Center?: string;
	/** Partner - prevádzka. */
	Partner_Department?: string;
	/** Partner - Fakturačná adresa - ulica. */
	Partner_Street?: string;
	/** Partner - Fakturačná adresa - ulica číslo. */
	Partner_Street_No?: string;
	/** Partner - Fakturačná adresa - PSČ. */
	Partner_Postcode?: string;
	/** Partner - Fakturačná adresa - mesto. */
	Partner_City?: string;
	/** Partner - Fakturačná adresa - štát. */
	Partner_State?: string;
	/** Partner - Fakturačná adresa - EAN fakturačného miesta. */
	Partner_Billing_Place_Ean?: string;
	/** Partner - Korešpondenčná adresa - ulica. */
	Partner_Pa_Street?: string;
	/** Partner - Korešpondenčná adresa - ulica číslo. */
	Partner_Pa_Street_No?: string;
	/** Partner - Korešpondenčná adresa - PSČ. */
	Partner_Pa_Postcode?: string;
	/** Partner - Korešpondenčná adresa - mesto. */
	Partner_Pa_City?: string;
	/** Partner - Korešpondenčná adresa - štát. */
	Partner_Pa_State?: string;
	/** Partner - Dodacia adresa - ulica. */
	Partner_Da_Street?: string;
	/** Partner - Dodacia adresa - ulica číslo. */
	Partner_Da_Street_No?: string;
	/** Partner - Dodacia adresa - PSČ. */
	Partner_Da_Postcode?: string;
	/** Partner - Dodacia adresa - mesto. */
	Partner_Da_City?: string;
	/** Partner - Dodacia adresa - štát. */
	Partner_Da_State?: string;
	/** Partner - Dodacia adresa - EAN miesta dodania (pobočky). */
	Partner_Da_Delivery_Place_Ean?: string;
	/** Názov partnera. */
	Partner_Name?: string;
	/** Partner - Korešpondenčná adresa - názov */
	Partner_Pa_Name?: string;
	/** Partner - Dodacia adresa - názov */
	Partner_Da_Name?: string;
	/** Číslo pôvodného dokladu (platné pre dobropisy). */
	Original_Number?: string;
	/** Kľúč záznamu v externej DB. Ak je zadaný tak slúži ako párovacie kritérium. */
	Guid_Ext?: string;
	/** Partner - email. */
	Partner_Email?: string;
	/** Partner - meno. */
	Partner_FirstName?: string;
	/** Partner - priezvisko. */
	Partner_Surname?: string;
	/** Partner - telefón. */
	Partner_Telephone_Number?: string;
	/**
	 * Zámok dokladu - môže obsahovať hodnoty: zamknutý, odomknutý.
	 * Pri editácii dokladu nie je možné zmeniť hodnotu zamknutý na odomknutý.
	 */
	Lock?: string;
	/** Používateľ - obchodník z dokladu. */
	User?: string;
	/** Interné rozúčtovanie 1 - názov. */
	Doc_Ia_Name_1?: string;
	/** Interné rozúčtovanie 1 - kód. */
	Doc_Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - názov. */
	Doc_Ia_Name_2?: string;
	/** Interné rozúčtovanie 2 - kód. */
	Doc_Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - názov. */
	Doc_Ia_Name_3?: string;
	/** Interné rozúčtovanie 3 - kód. */
	Doc_Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - názov. */
	Doc_Ia_Name_4?: string;
	/** Interné rozúčtovanie 4 - kód. */
	Doc_Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - názov. */
	Doc_Ia_Name_5?: string;
	/** Interné rozúčtovanie 5 - kód. */
	Doc_Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - názov. */
	Doc_Ia_Name_6?: string;
	/** Interné rozúčtovanie 6 - kód. */
	Doc_Ia_Code_6?: string;
	/** Interné rozúčtovanie 1 - prevodka - názov. */
	Doc_Transfer_Ia_Name_1?: string;
	/** Interné rozúčtovanie 1 - prevodka - kód. */
	Doc_Transfer_Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - prevodka - názov. */
	Doc_Transfer_Ia_Name_2?: string;
	/** Interné rozúčtovanie 2 - prevodka - kód. */
	Doc_Transfer_Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - prevodka - názov. */
	Doc_Transfer_Ia_Name_3?: string;
	/** Interné rozúčtovanie 3 - prevodka - kód. */
	Doc_Transfer_Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - prevodka - názov. */
	Doc_Transfer_Ia_Name_4?: string;
	/** Interné rozúčtovanie 4 - prevodka - kód. */
	Doc_Transfer_Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - prevodka - názov. */
	Doc_Transfer_Ia_Name_5?: string;
	/** Interné rozúčtovanie 5 - prevodka - kód. */
	Doc_Transfer_Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - prevodka - názov. */
	Doc_Transfer_Ia_Name_6?: string;
	/** Interné rozúčtovanie 6 - prevodka - kód. */
	Doc_Transfer_Ia_Code_6?: string;
	/** Číslo obchodného prípadu. */
	Commission?: string;
	/** Celková hmotnosť dokladu (kg). */
	Weight_Stock_Items?: number;
	/** Položky dokladu. */
	Items?: DtoDocumentItemGet[];
	/** `Enclosures`. */
	Enclosures?: DtoDocumentEnclosure[];
	/**
	 * Príznak, či sa na doklade pracuje so skladačkou, podpoložkami, alebo sa toto nastavenie preberá z karty.
	 *  Composites - Skladačky
	 *  SubItems - Podpoložky
	 *  FromStockItem - Prebrať z karty
	 */
	Pv_Accept_Composites?: string;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre doklad. */
export interface DtoDocumentPost {
	/**
	 * Externý identifikátor slúži na komunikáciu cez API.
	 * Identifikátor bude vrátený v odpovedi na request, aby ste dokázali identifikovať ku ktorému záznamu patria odpovede poslané ako response.
	 * Hodnota sa neukladá, ale mala by byť jedinečná.
	 */
	RecordExternalIdentificator: string;
	/** Poznámka. */
	Doc_Description?: string;
	/**
	 * Poznámka s HTML formátovaným textom.
	 * Pozor: Je potrebné, aby vkladaný html text bol správne escape-nutý pre json.
	 * Dá sa použiť napríklad online nástroj: https://www.freeformatter.com/json-escape.html
	 */
	Doc_Description_Html?: string;
	/** Úvodný text. */
	Introduction_Text?: string;
	/** Záverečný text. */
	Final_Text?: string;
	/** Dodacie a platobné podmienky. */
	Delivery_Text?: string;
	/** Predmet. */
	Subject?: string;
	/**
	 * Dátum vyhotovenia dokladu.
	 * Rok dátumu slúži ako párovacie kritérium dokladu. Ak dátum nie je zadaný, pri párovaní sa ignoruje a doklad sa hľadá medzi všetkými dokladmi.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Document?: string;
	/**
	 * Dátum prijatia.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Admission?: string;
	/**
	 * Dátum splatnosti.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Due?: string;
	/**
	 * Dátum vzniku daňovej povinnosti.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Chargebility_Date?: string;
	/**
	 * Dátum pre sadzby DPH.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Vatrate?: string;
	/**
	 * Dátum a čas výdaja zo skladu.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Release?: string;
	/**
	 * Dátum predpokladanej realizácie.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Exp_Realization?: string;
	/**
	 * Dátum skutočnej realizácie.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Realization?: string;
	/**
	 * Dátum dodania.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Delivery_Date?: string;
	/**
	 * Dátum a čas príjmu na sklad.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Receive?: string;
	/**
	 * Dátum platnosti dokladu.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Validity?: string;
	/**
	 * Dátum rezervácie.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Reservation_Doc?: string;
	/** Spôsob dopravy. */
	Transport_Type?: string;
	/** Forma úhrady. */
	Payment_Type?: string;
	/**
	 * Kurz meny dokladu.
	 * Pri editácii dokladu ho nie je možné zmeniť.
	 */
	Exchange_Rate?: number;
	/**
	 * Mena dokladu.
	 * Pri editácii dokladu ju nie je možné zmeniť.
	 */
	Curr?: string;
	/** Cieľový sklad názov - prevodka. */
	Stock_Transfer_Name?: string;
	/** Kód číselného radu. Ak je zadaný tak slúži ako párovacie kritérium. */
	Ns_Code?: string;
	/** Kód evidencie. Ak je zadaný tak slúži ako párovacie kritérium. */
	Ns_Evid_Code?: string;
	/** Číslo dokladu. Slúži ako párovacie kritérium dokladu. */
	Ns_Number?: string;
	/** Číslo účtu (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Account_Number?: string;
	/** Variabilný symbol. */
	Variable_Symbol?: string;
	/** Špecifický symbol. */
	Specific_Symbol?: string;
	/** Kód banky (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Bank_Code?: string;
	/** Konštantný symbol. */
	Constant_Symbol?: string;
	/** Externé číslo dokladu. */
	External_Number?: string;
	/** Číslo účtu vo formáte IBAN (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Iban?: string;
	/** SWIFT kód banky (predajné doklady - môj účet, nákupné doklady - účet partnera). */
	Swift?: string;
	/**
	 * Spôsob výpočtu celkovej sumy dokladu.
	 * 1 - Bez DPH,
	 * 2 - S DPH.
	 */
	Total_Price_Calculation?: 1 | 2;
	/** Stav dokladu. */
	Document_State?: string;
	/** Číslo partnera. */
	Ns_Number_Partner?: string;
	/** EAN partnera. */
	Partner_Ean?: string;
	/** IČO partnera. */
	Partner_Reg?: string;
	/** DIČ partnera. */
	Partner_Tax?: string;
	/** Partner - IČ DPH. */
	Partner_Vat_No?: string;
	/** Partner - stredisko. */
	Partner_Center?: string;
	/** Partner - prevádzka. */
	Partner_Department?: string;
	/** Partner - Fakturačná adresa - ulica. */
	Partner_Street?: string;
	/** Partner - Fakturačná adresa - ulica číslo. */
	Partner_Street_No?: string;
	/** Partner - Fakturačná adresa - PSČ. */
	Partner_Postcode?: string;
	/** Partner - Fakturačná adresa - mesto. */
	Partner_City?: string;
	/** Partner - Fakturačná adresa - štát. */
	Partner_State?: string;
	/** Partner - Fakturačná adresa - EAN fakturačného miesta. */
	Partner_Billing_Place_Ean?: string;
	/** Partner - Korešpondenčná adresa - ulica. */
	Partner_Pa_Street?: string;
	/** Partner - Korešpondenčná adresa - ulica číslo. */
	Partner_Pa_Street_No?: string;
	/** Partner - Korešpondenčná adresa - PSČ. */
	Partner_Pa_Postcode?: string;
	/** Partner - Korešpondenčná adresa - mesto. */
	Partner_Pa_City?: string;
	/** Partner - Korešpondenčná adresa - štát. */
	Partner_Pa_State?: string;
	/** Partner - Dodacia adresa - ulica. */
	Partner_Da_Street?: string;
	/** Partner - Dodacia adresa - ulica číslo. */
	Partner_Da_Street_No?: string;
	/** Partner - Dodacia adresa - PSČ. */
	Partner_Da_Postcode?: string;
	/** Partner - Dodacia adresa - mesto. */
	Partner_Da_City?: string;
	/** Partner - Dodacia adresa - štát. */
	Partner_Da_State?: string;
	/** Partner - Dodacia adresa - EAN miesta dodania (pobočky). */
	Partner_Da_Delivery_Place_Ean?: string;
	/** Názov partnera. */
	Partner_Name?: string;
	/** Partner - Korešpondenčná adresa - názov */
	Partner_Pa_Name?: string;
	/** Partner - Dodacia adresa - názov */
	Partner_Da_Name?: string;
	/** Číslo pôvodného dokladu (platné pre dobropisy). */
	Original_Number?: string;
	/** Kľúč záznamu v externej DB. Ak je zadaný tak slúži ako párovacie kritérium. */
	Guid_Ext?: string;
	/**
	 * Typ partnera.
	 * -2 - Občan,
	 * 1 - Podnikateľ - fyzická osoba,
	 * 2 - Podnikateľ - právnická osoba.
	 */
	Partner_Type?: -2 | 1 | 2 | 0;
	/** Partner - email. */
	Partner_Email?: string;
	/** Partner - meno. */
	Partner_FirstName?: string;
	/** Partner - priezvisko. */
	Partner_Surname?: string;
	/** Partner - telefón. */
	Partner_Telephone_Number?: string;
	/**
	 * Partner - Platiteľ DPH.
	 * 1 - Zapnuté
	 * 2 - Vypnuté
	 */
	Partner_Vat_Payer?: number;
	/** Partner - kľúč záznamu v externej DB.. */
	Partner_Guid_Ext?: string;
	/** Prednastavený defaultný sklad - názov. */
	Stock_Predefined_Name?: string;
	/** Prednastavený defaultný sklad - kód. */
	Stock_Predefined_Code?: string;
	/** Cieľový sklad kód - prevodka. */
	Stock_Transfer_Code?: string;
	/**
	 * Zámok dokladu - môže obsahovať hodnoty: zamknutý, odomknutý.
	 * Pri editácii dokladu nie je možné zmeniť hodnotu zamknutý na odomknutý.
	 */
	Lock?: string;
	/** Používateľ - obchodník z dokladu. */
	User?: string;
	/** Interné rozúčtovanie 1 - názov. */
	Doc_Ia_Name_1?: string;
	/** Interné rozúčtovanie 1 - kód. */
	Doc_Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - názov. */
	Doc_Ia_Name_2?: string;
	/** Interné rozúčtovanie 2 - kód. */
	Doc_Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - názov. */
	Doc_Ia_Name_3?: string;
	/** Interné rozúčtovanie 3 - kód. */
	Doc_Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - názov. */
	Doc_Ia_Name_4?: string;
	/** Interné rozúčtovanie 4 - kód. */
	Doc_Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - názov. */
	Doc_Ia_Name_5?: string;
	/** Interné rozúčtovanie 5 - kód. */
	Doc_Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - názov. */
	Doc_Ia_Name_6?: string;
	/** Interné rozúčtovanie 6 - kód. */
	Doc_Ia_Code_6?: string;
	/** Interné rozúčtovanie 1 - prevodka - názov. */
	Doc_Transfer_Ia_Name_1?: string;
	/** Interné rozúčtovanie 1 - prevodka - kód. */
	Doc_Transfer_Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - prevodka - názov. */
	Doc_Transfer_Ia_Name_2?: string;
	/** Interné rozúčtovanie 2 - prevodka - kód. */
	Doc_Transfer_Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - prevodka - názov. */
	Doc_Transfer_Ia_Name_3?: string;
	/** Interné rozúčtovanie 3 - prevodka - kód. */
	Doc_Transfer_Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - prevodka - názov. */
	Doc_Transfer_Ia_Name_4?: string;
	/** Interné rozúčtovanie 4 - prevodka - kód. */
	Doc_Transfer_Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - prevodka - názov. */
	Doc_Transfer_Ia_Name_5?: string;
	/** Interné rozúčtovanie 5 - prevodka - kód. */
	Doc_Transfer_Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - prevodka - názov. */
	Doc_Transfer_Ia_Name_6?: string;
	/** Interné rozúčtovanie 6 - prevodka - kód. */
	Doc_Transfer_Ia_Code_6?: string;
	/** Číslo obchodného prípadu. */
	Commission?: string;
	/** Položky dokladu. */
	Items?: DtoDocumentItemPost[];
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre dáta prílohy. */
export interface DtoEnclosureDataGet {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/**
	 * Príloha
	 * @format byte (base64-encoded string)
	 */
	Enclosure?: string;
	/**
	 * Príloha v malom formáte (ak je prílohou obrázok)
	 * @format byte (base64-encoded string)
	 */
	EnclosureView?: string;
}

/** DTO trieda pre obálku prílohy skupiny skladovej karty. */
export interface DtoGroupEnclosure {
	/**
	 * ID záznamu. Používa sa ako parameter pre načítanie prílohy, pre endpoint /api/v1/enclosures
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov prílohy */
	Name?: string;
	/** Popis prílohy */
	Description?: string;
	/** Prípona súboru prílohy */
	Extension?: string;
	/** Či sa jedná o hlavný obrázok hlavného záznamu */
	Is_Default?: number;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre skupiny skladových kariet, služieb, zariadení */
export interface DtoGroups {
	/**
	 * Id skupiny
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Číslo skupiny */
	Ns_Number?: string;
	/** Kód skupiny */
	Ns_Code?: string;
	/** Názov skupiny */
	Name?: string;
	/**
	 * Id predka skupiny
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Parent?: number;
	/** Popis skupiny */
	Info?: string;
	/**
	 * História - dátum zmeny skupiny
	 * @format date-time (ISO 8601 string)
	 */
	Date_Changed?: string;
	/** `Enclosures`. */
	Enclosures?: DtoGroupEnclosure[];
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre interné rozúčtovanie. */
export interface DtoInternalAccountingGet {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Variant interného rozúčtovania */
	Variant?: number;
	/**
	 * IdRecord nadradenej hodnoty v strome
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Parent?: number;
	/** Strom - Zoznam predchodcov */
	Tree_Parents?: string;
	/** Strom - Úroveň */
	Tree_Level?: number;
	/** Poradové číslo */
	Ordinal?: number;
	/** Názov */
	Name?: string;
	/** Interné rozúčtovanie je rozpis (-1 znamená, že ide o rozpis, 0 znamená, že nejde o rozpis) */
	Is_Breakdown?: number;
	/** Kód interného rozúčtovania */
	Code?: string;
	/** Kód číselného radu */
	Ns_Code?: string;
	/** Kód evidencie */
	Ns_Evid_Code?: string;
	/** Číslo interného rozúčtovania */
	Ns_Number?: string;
	/** Kľúč záznamu v externej DB. Ak je zadaný, tak slúži ako párovacie kritérium */
	Guid_Ext?: string;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre interné rozúčtovanie. */
export interface DtoInternalAccountingPost {
	/**
	 * Externý identifikátor slúži na komunikáciu cez API.
	 * Identifikátor bude vrátený v odpovedi na request, aby ste dokázali identifikovať ku ktorému záznamu patria odpovede poslané ako response.
	 * Hodnota sa neukladá, ale mala by byť jedinečná.
	 */
	RecordExternalIdentificator: string;
	/** Názov */
	Name?: string;
	/** Kód interného rozúčtovania */
	Code?: string;
	/** Kód číselného radu */
	Ns_Code?: string;
	/** Číslo interného rozúčtovania */
	Ns_Number?: string;
	/** Kľúč záznamu v externej DB. Ak je zadaný, tak slúži ako párovacie kritérium */
	Guid_Ext?: string;
	/** Klúč nadradeného záznamu v externej DB */
	Guid_Ext_Parent?: string;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** Adresa parnera */
export interface DtoPartnerAddress {
	/**
	 * Typ adresy.
	 * Sídlo firmy alebo trvalé bydlisko = 1
	 * Prechodné bydlisko = 2
	 * Fakturačná adresa = 3
	 * Dodacia adresa = 4
	 * Kontaktná adresa = 5
	 * Korešpondenčná adresa = 6
	 * Iba trvalé bydlisko = 7
	 */
	Address_Type?: number;
	/** Názov. */
	Name?: string;
	/** Ulica. */
	Street?: string;
	/** PSČ. */
	Postcode?: string;
	/** Mesto. */
	City?: string;
	/**
	 * Korešpondenčná adresa.
	 * Áno = -1
	 * Nie = 0
	 */
	Is_Postcard_Address?: number;
	/**
	 * Dodacia adresa.
	 * Áno = -1
	 * Nie = 0
	 */
	Is_Delivery_Address?: number;
	/**
	 * Predvolené pre daný typ.
	 * Áno = -1
	 * Nie = 0
	 */
	Is_Default_For_Type?: number;
	/** Číslo ulice. */
	Street_No?: string;
	/** Štát. */
	State?: string;
	/** EAN fakturačného miesta. */
	Billing_Place_Ean?: string;
	/** Dodacia adresa - EAN miesta dodania (pobočky). */
	Delivery_Place_Ean?: string;
}

/** Bankový účet partnera */
export interface DtoPartnerBankAccount {
	/** Číslo účtu */
	Account_No?: string;
	/** Názov účtu */
	Name?: string;
	/** IBAN */
	Iban?: string;
	/** Variabilný symbol */
	Variable_Symbol?: string;
	/** Špecifický symbol */
	Specific_Symbol?: string;
	/**
	 * Predvolený účet.
	 * Áno = -1
	 * Nie = 0
	 */
	Is_Default?: number;
	/** Mena */
	Curr_Code?: string;
	/** Konštantný symbol */
	Const_Symbol?: string;
	/** SWIFT */
	Swift?: string;
	/** Kód banky */
	Bank_Code?: string;
}

/** Kontakt partnera */
export interface DtoPartnerContact {
	/** Krstné meno */
	Forname?: string;
	/** Priezvisko */
	Surname?: string;
	/**
	 * Predvolený kontakt.
	 * Áno = -1
	 * Nie = 0
	 */
	Is_Default?: number;
	/**
	 * Zoznam emailov, telefónnych čísiel pre tento daný kontakt partnera.
	 * @readonly
	 */
	ContactsData?: DtoPartnerContactData[];
}

/** Dáta pre kontakt partnera */
export interface DtoPartnerContactData {
	/**
	 * Typ kontaktu.
	 * Telefón = 1
	 * Telefón2 = 2
	 * Email = 3
	 * Http = 4
	 * ICQ = 5
	 * Skype = 6
	 * Ostatné = 7
	 */
	Type?: number;
	/** Kontakt */
	Data?: string;
	/** Tel. číslo */
	Tel_Number?: string;
}

/** DTO trieda pre individuálne ceny partnerov za skupinu kariet */
export interface DtoPartnerSIGroupPricingLists {
	/**
	 * ID skupiny skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItemGroup_IdRecord?: number;
	/** Číslo skupiny skladovej karty */
	StockItemGroup_Ns_Number?: string;
	/** Určuje prioritu cenníka (čím vyššie číslo, tým vyššiu prioritu má cenník) */
	StockItemGroup_TreeLevel?: number;
	/**
	 * Id partnera
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Partner_IdRecord?: number;
	/** Číslo partnera */
	Partner_Ns_Number?: string;
	/** IČO partnera */
	Partner_Reg?: string;
	/**
	 * Spôsob výpočtu ceny
	 * 1 - Fixná cena
	 * 2 - Manažérska cena + marža
	 * 3 - Skladová cena + marža
	 * 4 - Cena z iného cenníka - zľava
	 */
	CalculationType?: number;
	/**
	 * Id cenníka
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	CalculationType_PricingList_IdRecord?: number;
	/** Kód cenníka */
	CalculationType_PricingList_Code?: string;
	/** Zľava alebo marža (%) */
	CalculationType_Percentage?: number;
}

/** DTO trieda pre partnera. */
export interface DtoPartnersGet {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/**
	 * Zoznam adries partnera.
	 * @readonly
	 */
	Addresses?: DtoPartnerAddress[];
	/**
	 * Zoznam bankových účtov partnera.
	 * @readonly
	 */
	BankAccounts?: DtoPartnerBankAccount[];
	/**
	 * Zoznam kontaktov partnera.
	 * @readonly
	 */
	Contacts?: DtoPartnerContact[];
	/** Názov partnera. */
	Name?: string;
	/** Poznámka. */
	Description?: string;
	/** Číslo partnera. */
	Ns_Number?: string;
	/** EAN partnera. */
	Partner_Ean?: string;
	/** IČO. */
	Reg?: string;
	/** DIČ. */
	Tax?: string;
	/**
	 * História - dátum zmeny partnera.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Changed?: string;
	/** Splatnosť odoslaných dokladov. */
	Maturity_Sendedinvoices?: number;
	/** Splatnosť prijatých dokladov. */
	Maturity_Receivedinvoices?: number;
	/** Stredisko. */
	Center?: string;
	/** Prevádzka. */
	Department?: string;
	/** Spôsob dopravy. */
	Transport_Type?: string;
	/** Forma úhrady. */
	Payment_Type?: string;
	/** Klúč záznamu v externom SW. */
	Guid_Ext?: string;
	/**
	 * Nastavenie fakturačného kreditu.
	 * 0 - Vypnuté,
	 * 1 - Povoliť - iba upozornenie,
	 * 2 - Zakázať - tvrdá validácia.
	 */
	Credit_Settings?: 0 | 1 | 2;
	/** Suma fakturačného kreditu. */
	Credit_Value?: number;
	/**
	 * Zakázať fakturáciu, ak je neplatič.
	 * -1 - Zakázať,
	 * 0 - Povoliť.
	 */
	Credit_Unpayer?: number;
	/**
	 * Typ partnera na doklade.
	 * Občan = -2
	 * Podnikateľ - fyzická osoba = 1
	 * Podnikateľ - právnická osoba = 2
	 */
	Partner_Type?: -2 | 1 | 2 | 0;
	/** IČ DPH. */
	Vat_No?: string;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre partnera. */
export interface DtoPartnersPost {
	/**
	 * Externý identifikátor slúži na komunikáciu cez API.
	 * Identifikátor bude vrátený v odpovedi na request, aby ste dokázali identifikovať ku ktorému záznamu patria odpovede poslané ako response.
	 * Hodnota sa neukladá, ale mala by byť jedinečná.
	 */
	RecordExternalIdentificator: string;
	/** Názov partnera. */
	Name?: string;
	/** Poznámka. */
	Description?: string;
	/** Číslo partnera. */
	Ns_Number?: string;
	/** EAN partnera. */
	Partner_Ean?: string;
	/** IČO. */
	Reg?: string;
	/** DIČ. */
	Tax?: string;
	/** Splatnosť odoslaných dokladov. */
	Maturity_Sendedinvoices?: number;
	/** Splatnosť prijatých dokladov. */
	Maturity_Receivedinvoices?: number;
	/** Stredisko. */
	Center?: string;
	/** Prevádzka. */
	Department?: string;
	/** Spôsob dopravy. */
	Transport_Type?: string;
	/** Forma úhrady. */
	Payment_Type?: string;
	/** Klúč záznamu v externom SW. */
	Guid_Ext?: string;
	/**
	 * Typ partnera na doklade.
	 * Občan = -2
	 * Podnikateľ - fyzická osoba = 1
	 * Podnikateľ - právnická osoba = 2
	 */
	Partner_Type?: -2 | 1 | 2 | 0;
	/** IČ DPH. */
	Vat_No?: string;
	/**
	 * Platiteľ DPH.
	 * 1 - Zapnuté
	 * 2 - Vypnuté
	 */
	Vat_Payer?: number;
	/** Fakturačná adresa - PSČ. */
	PostCode?: string;
	/** Fakturačná adresa - Ulica. */
	Street?: string;
	/** Fakturačná adresa - Ulica - číslo. */
	StreetNo?: string;
	/** Fakturačná adresa - Mesto. */
	City?: string;
	/** Fakturačná adresa - Štát. */
	State?: string;
	/** Fakturačná adresa - EAN fakturačného miesta. */
	BillingPlaceEan?: string;
	/** Korešpondenčná adresa - PSČ. */
	PaPostCode?: string;
	/** Korešpondenčná adresa - Ulica. */
	PaStreet?: string;
	/** Korešpondenčná adresa - Ulica - číslo. */
	PaStreetNo?: string;
	/** Korešpondenčná adresa - Mesto. */
	PaCity?: string;
	/** Korešpondenčná adresa - Štát. */
	PaState?: string;
	/** Korešpondenčná adresa - Názov. */
	PaName?: string;
	/** Dodacia adresa - PSČ. */
	DaPostCode?: string;
	/** Dodacia adresa - Ulica. */
	DaStreet?: string;
	/** Dodacia adresa - Ulica - číslo. */
	DaStreetNo?: string;
	/** Dodacia adresa - Mesto. */
	DaCity?: string;
	/** Dodacia adresa - Štát. */
	DaState?: string;
	/** Dodacia adresa - Názov. */
	DaName?: string;
	/** Dodacia adresa - EAN miesta dodania (pobočky). */
	DaDeliveryPlaceEan?: string;
	/** Kontakt - meno. */
	ContactFirstName?: string;
	/** Kontakt - priezvisko. */
	ContactSurname?: string;
	/** Kontakt - telefónne číslo. */
	ContactTelephoneNumber?: string;
	/** Kontakt - Email. */
	ContactEmail?: string;
	/** Názov účtu. */
	AccountName?: string;
	/** IBAN. */
	Iban?: string;
	/** SWIFT. */
	Swift?: string;
	/** Číslo účtu. */
	AccountNumber?: string;
	/** Kód banky. */
	BankCode?: string;
	/** Mena bankového účtu. */
	AccountCurr?: string;
	/** Variabilný symbol. */
	VariableSymbol?: string;
	/** Konštantný symbol. */
	ConstantSymbol?: string;
	/** Špecifický symbol. */
	SpecificSymbol?: string;
	/** Interné rozúčtovanie 1 - názov. */
	Ia_Name_1?: string;
	/** Interné rozúčtovanie 2 - názov. */
	Ia_Name_2?: string;
	/** Interné rozúčtovanie 3 - názov. */
	Ia_Name_3?: string;
	/** Interné rozúčtovanie 4 - názov. */
	Ia_Name_4?: string;
	/** Interné rozúčtovanie 5 - názov. */
	Ia_Name_5?: string;
	/** Interné rozúčtovanie 6 - názov. */
	Ia_Name_6?: string;
	/** Interné rozúčtovanie 1 - kód. */
	Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - kód. */
	Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - kód. */
	Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - kód. */
	Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - kód. */
	Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - kód. */
	Ia_Code_6?: string;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre cenníky */
export interface DtoPricingLists {
	/**
	 * ID skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItem_IdRecord?: number;
	/** Číslo skladovej karty */
	StockItem_Ns_Number?: string;
	/**
	 * Typ skladovej karty.
	 * 1 - Skladová karta
	 * 2 - Služba
	 * 6 - Zariadenie
	 */
	StockItem_Type?: number;
	/**
	 * ID partnera
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Partner_IdRecord?: number;
	/** Číslo partnera */
	Partner_Ns_Number?: string;
	/** IČO partnera */
	Partner_Reg?: string;
	/** Cena bez DPH */
	Price?: number;
}

/** Príslušenstvo skladovej karty */
export interface DtoStockItemAndServiceAccessory {
	/**
	 * Id skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItems_IdRecord?: number;
	/** Poradie */
	Order?: number;
	/** Názov karty */
	Name?: string;
	/** Množstvo */
	Amount?: number;
	/** Merná jednodka */
	MeasureUnit?: string;
	/** Kód karty */
	StockItemsNsNumber?: string;
}

/** Alternatíva skladovej karty */
export interface DtoStockItemAndServiceAlternative {
	/**
	 * Id karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItems_IdRecord?: number;
	/** Poradie */
	Order?: number;
	/** Kód karty */
	StockItemsNsNumber?: string;
	/** Názov karty */
	Name?: string;
	/** Množstvo */
	Amount?: number;
	/** Merná jednotka */
	MeasureUnit?: string;
	/** Úplná náhrada */
	FullExchange?: number;
}

/** Zostatok skladovej karty */
export interface DtoStockItemBalance {
	/**
	 * ID skladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockId?: number;
	/** Kód skladu */
	StockCode?: string;
	/** Názov skladu */
	StockName?: string;
	/** Zostatok skladovej karty */
	Balance?: number;
	/** Rezervované množstvo skladovej karty */
	Reservated?: number;
	/** Dostupné množstvo */
	Available?: number;
	/** Skladová cena */
	StockPrice?: number;
}

/** Kód skladovej karty */
export interface DtoStockItemCode {
	/**
	 * Indikuje, či daný kód je hlavný kód karty.
	 * -1 - Je hlavným kódom karty.
	 * 0 - Nie je hlavným kódom karty.
	 */
	Is_Default?: number;
	/** Typ kódu (EAN, ITF14, ...) */
	Type_Name?: string;
	/** Kód skladovej karty */
	Code?: string;
	/** Kód mernej jednotky */
	MuCode?: string;
}

/** DTO trieda pre obálku prílohy skladovej karty. */
export interface DtoStockItemEnclosure {
	/**
	 * ID záznamu. Používa sa ako parameter pre načítanie prílohy, pre endpoint /api/v1/enclosures
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov prílohy */
	Name?: string;
	/** Popis prílohy */
	Description?: string;
	/** Prípona súboru prílohy */
	Extension?: string;
	/** Či sa jedná o hlavný obrázok hlavného záznamu */
	Is_Default?: number;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** Skupina skladovej karty */
export interface DtoStockItemGroup {
	/**
	 * Id skupiny
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItems_IdRecord?: number;
	/** Číslo skupiny */
	Ns_Number?: string;
	/** Kód skupiny */
	Ns_Code?: string;
	/** Názov skupiny */
	Name?: string;
	/**
	 * Id predka skupiny
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdParent?: number;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** Parameter skladovej karty */
export interface DtoStockItemMeasureUnit {
	/** Názov MJ */
	Name?: string;
	/** Kód MJ */
	Code?: string;
	/** Koeficient prepočtu MJ voči hlavnej MJ */
	Coefficient?: number;
	/**
	 * Indikuje, či daná MJ je hlavnou MJ karty.
	 * -1 - Je hlavnou mj karty.
	 * 0 - Nie je hlavnou mj karty.
	 */
	Is_Default?: number;
}

/** Parameter skladovej karty */
export interface DtoStockItemParam {
	/** Názov parametra */
	Name?: string;
	/** Hodnota parametra */
	Value?: string;
	/** Merná jednotka */
	MeasureUnit?: string;
}

/** Onix `DtoStockItemPartner` DTO (generated from docs/V1.json). */
export interface DtoStockItemPartner {
	/** Kód karty u partnera */
	PartnerStockItemCode?: string;
	/**
	 * Indikuje o aký typ partnera sa jedná.
	 * 1 -&gt; Dodávateľ.
	 * 2 -&gt; Konkurent.
	 * 3 -&gt; Klient.
	 */
	PartnerType?: number;
	/** Názov partnera */
	PartnerName?: string;
	/** Názov karty u partnera */
	PartnerStockItemName?: string;
	/** Merná jednotka */
	PartnerMeasureUnit?: string;
}

/** Zostatok skladovej karty, kombinacia karta - sklad - vlastnosť dávky */
export interface DtoStockItemPropBalance {
	/**
	 * ID skladu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockId?: number;
	/** Názov skladu */
	StockName?: string;
	/**
	 * ID skladovej karty
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	StockItemId?: number;
	/** Hodnota vlastnosti dávky */
	PropertyText?: string;
	/**
	 * ID vlastnosti dávky
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	PropertyId?: number;
	/** Zostatok */
	Balance?: number;
}

/** DTO trieda pre skladovú kartu. */
export interface DtoStockItemsGet {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov skladovej karty. */
	Name?: string;
	/**
	 * Pre POST platí, že sa posiela hodnota enum:
	 * Typ manažérskeho ocenenia
	 * 1 - Manažérska cena = legislatívna,
	 * 7 - Fixná cena.
	 *
	 * Pre GET platí, že vracia hodnoty:
	 * 0 - Nezadaná,
	 * 1 - Manažérska cena = legislatívna,
	 * 7 - Fixná cena.
	 */
	Managerial_Price_Type?: number;
	/** Fixná cena. */
	Managerial_Price?: number;
	/** Popis. */
	Info?: string;
	/** Účet karty - syntetika. */
	Account_Stock_Syn?: string;
	/** Účet karty - analytika. */
	Account_Stock_Anl?: string;
	/** Nákladový účet - syntetika. */
	Account_Issue_Syn?: string;
	/** Nákladový účet - analytika. */
	Account_Issue_Anl?: string;
	/** Účet obstarania - syntetika. */
	Account_Recive_Syn?: string;
	/** Účet obstarania - analytika. */
	Account_Recive_Anl?: string;
	/** Účet fakturácie - syntetika. */
	Account_Profit_Syn?: string;
	/** Účet fakturácie - analytika. */
	Account_Profit_Anl?: string;
	/** Predajná cena bez DPH. */
	Default_Price?: number;
	/** Predajná cena s DPH. */
	Default_Price_Vat?: number;
	/** Intrastat - Kód kombinovanej nomenklatúry. */
	Ist_Code?: string;
	/** Intrastat - Koeficient prepočtu na DMJ. */
	Ist_Dmj?: number;
	/** Intrastat - Čistá hmotnosť hlavnej MJ (kg). */
	Ist_Weight?: number;
	/** Intrastat - Krajina pôvodu. */
	Ist_Country_Name?: string;
	/** Intrastat - Opis tovaru. */
	Ist_Description?: string;
	/** Kódy dodávateľov skladovej karty. */
	Supplier_Codes?: string;
	/** Recyklačný poplatok - Sadzba EUR/kg. */
	Recycle_Rate_Per_Kg?: number;
	/** Recyklačný poplatok. */
	Recycle_Tax?: number;
	/** Hmotnosť hlavnej MJ v kg. */
	Weight?: number;
	/** Názov hlavnej mernej jednotky. */
	Measure_Units_Default_Name?: string;
	/** Hlavný kód produktu. */
	Product_Code?: string;
	/** Kód číselného radu. */
	Ns_Code?: string;
	/** Čislo karty. Slúži ako párovacie kritérium skladovej karty. */
	Ns_Number: string;
	/**
	 * Plu.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Plu?: number;
	/** Karta s výrobnými číslami. */
	Use_Serial_Number?: boolean;
	/** Karta s dátumami expirácie. */
	Monitor_Expiration?: boolean;
	/**
	 * Skladový zostatok karty.
	 * @readonly
	 */
	StockItemBalance?: DtoStockItemBalance[];
	/**
	 * Skupiny skladovej karty
	 * @readonly
	 */
	StockItemGroups?: DtoStockItemGroup[];
	/**
	 * Parametre skladovej karty
	 * @readonly
	 */
	StockItemParams?: DtoStockItemParam[];
	/**
	 * Kódy skladovej karty
	 * @readonly
	 */
	StockItemCodes?: DtoStockItemCode[];
	/**
	 * Príslušenstvo skladovej karty
	 * @readonly
	 */
	StockItemAccessories?: DtoStockItemAndServiceAccessory[];
	/** `Enclosures`. */
	Enclosures?: DtoStockItemEnclosure[];
	/**
	 * Pre POST platí, že sa posiela hodnota enum:
	 * Sadzba DPH
	 * 1 - Základná
	 * 2 - Znížená
	 * 3 - Nulová
	 * 4 - Neobsahuje
	 * 5 - Znížená 2
	 *
	 * Pre GET platí, že vracia reťazec:
	 * Do 31.12.2024:
	 * "20" - Základná
	 * "10" - Znížená
	 * "0"  - Nulová
	 * "Neobsahuje" - Neobsahuje
	 *
	 * Od 1.1.2025:
	 * "23" - Základná
	 * "19" - Znížená
	 * "5" - Znížená 2
	 * "0"  - Nulová
	 * "Neobsahuje" - Neobsahuje
	 */
	VatRate?: string;
	/** Obvykle vydávané množstvo */
	Common_Mu_Amount?: number;
	/**
	 * Dátum zaevidovania
	 * @format date-time (ISO 8601 string)
	 */
	Date_Add?: string;
	/**
	 * História - dátum zmeny skladovej karty.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Changed?: string;
	/**
	 * Id hlavnej skupiny
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Stock_Items_Group_Default?: number;
	/** Obvykle vydávané množstvo - MJ */
	Common_Mu_Name?: string;
	/**
	 * Typ skladovej karty.
	 * 1 - Skladová karta
	 * 2 - Služba
	 * 6 - Zariadenie
	 */
	Type: "1" | "2" | "6";
	/**
	 * Alternatívy skladovej karty
	 * @readonly
	 */
	StockItemAlternatives?: DtoStockItemAndServiceAlternative[];
	/** Typ produktového kódu */
	Product_Code_Type?: string;
	/** Partner pre zariadenie – číslo partnera */
	Partner_Ns_Number?: string;
	/**
	 * Partner pre zariadenie – Id partnera
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Partner_IdRecord?: number;
	/** Partner pre zariadenie – názov partnera */
	Partner_Name?: string;
	/** Umiestnenie zariadenia */
	Location_Device?: string;
	/** Výrobné číslo zariadenia */
	Serial_Number_Device?: string;
	/**
	 * Zoznam dodávateľov skladovej karty
	 * @readonly
	 */
	StockItemPartners?: DtoStockItemPartner[];
	/**
	 * Zoznam merných jednotiek skladovej karty
	 * @readonly
	 */
	StockItemMeasureUnits?: DtoStockItemMeasureUnit[];
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre skladovú kartu. */
export interface DtoStockItemsPost {
	/**
	 * Externý identifikátor slúži na komunikáciu cez API.
	 * Identifikátor bude vrátený v odpovedi na request, aby ste dokázali identifikovať
	 * ku ktorému záznamu patria odpovede poslané ako response.
	 * Hodnota sa neukladá, ale mala by byť jedinečná.
	 */
	RecordExternalIdentificator: string;
	/** Názov skladovej karty. */
	Name?: string;
	/**
	 * Pre POST platí, že sa posiela hodnota enum:
	 * Typ manažérskeho ocenenia
	 * 1 - Manažérska cena = legislatívna,
	 * 7 - Fixná cena.
	 *
	 * Pre GET platí, že vracia hodnoty:
	 * 0 - Nezadaná,
	 * 1 - Manažérska cena = legislatívna,
	 * 7 - Fixná cena.
	 */
	Managerial_Price_Type?: number;
	/** Fixná cena. */
	Managerial_Price?: number;
	/** Popis. */
	Info?: string;
	/** Účet karty - syntetika. */
	Account_Stock_Syn?: string;
	/** Účet karty - analytika. */
	Account_Stock_Anl?: string;
	/** Nákladový účet - syntetika. */
	Account_Issue_Syn?: string;
	/** Nákladový účet - analytika. */
	Account_Issue_Anl?: string;
	/** Účet obstarania - syntetika. */
	Account_Recive_Syn?: string;
	/** Účet obstarania - analytika. */
	Account_Recive_Anl?: string;
	/** Účet fakturácie - syntetika. */
	Account_Profit_Syn?: string;
	/** Účet fakturácie - analytika. */
	Account_Profit_Anl?: string;
	/** Interné rozúčtovanie 1 - názov. */
	Ia_Name_1?: string;
	/** Interné rozúčtovanie 2 - názov. */
	Ia_Name_2?: string;
	/** Interné rozúčtovanie 3 - názov. */
	Ia_Name_3?: string;
	/** Interné rozúčtovanie 4 - názov. */
	Ia_Name_4?: string;
	/** Interné rozúčtovanie 5 - názov. */
	Ia_Name_5?: string;
	/** Interné rozúčtovanie 6 - názov. */
	Ia_Name_6?: string;
	/** Interné rozúčtovanie 1 - kód. */
	Ia_Code_1?: string;
	/** Interné rozúčtovanie 2 - kód. */
	Ia_Code_2?: string;
	/** Interné rozúčtovanie 3 - kód. */
	Ia_Code_3?: string;
	/** Interné rozúčtovanie 4 - kód. */
	Ia_Code_4?: string;
	/** Interné rozúčtovanie 5 - kód. */
	Ia_Code_5?: string;
	/** Interné rozúčtovanie 6 - kód. */
	Ia_Code_6?: string;
	/** Predajná cena bez DPH. */
	Default_Price?: number;
	/** Intrastat - Kód kombinovanej nomenklatúry. */
	Ist_Code?: string;
	/** Intrastat - Koeficient prepočtu na DMJ. */
	Ist_Dmj?: number;
	/** Intrastat - Čistá hmotnosť hlavnej MJ (kg). */
	Ist_Weight?: number;
	/** Intrastat - Opis tovaru. */
	Ist_Description?: string;
	/** Recyklačný poplatok - Sadzba EUR/kg. */
	Recycle_Rate_Per_Kg?: number;
	/** Recyklačný poplatok. */
	Recycle_Tax?: number;
	/** Hmotnosť hlavnej MJ v kg. */
	Weight?: number;
	/** Názov hlavnej mernej jednotky. */
	Measure_Units_Default_Name?: string;
	/** Hlavný kód produktu. */
	Product_Code?: string;
	/** Kód číselného radu. */
	Ns_Code?: string;
	/** Čislo karty. Slúži ako párovacie kritérium skladovej karty. */
	Ns_Number: string;
	/**
	 * Plu.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Plu?: number;
	/**
	 * Skladový zostatok karty.
	 * @readonly
	 */
	StockItemBalance?: DtoStockItemBalance[];
	/**
	 * Skupiny skladovej karty
	 * @readonly
	 */
	StockItemGroups?: DtoStockItemGroup[];
	/**
	 * Parametre skladovej karty
	 * @readonly
	 */
	StockItemParams?: DtoStockItemParam[];
	/**
	 * Kódy skladovej karty
	 * @readonly
	 */
	StockItemCodes?: DtoStockItemCode[];
	/**
	 * Príslušenstvo skladovej karty
	 * @readonly
	 */
	StockItemAccessories?: DtoStockItemAndServiceAccessory[];
	/**
	 * Pre POST platí, že sa posiela hodnota enum:
	 * Sadzba DPH
	 * 1 - Základná
	 * 2 - Znížená
	 * 3 - Nulová
	 * 4 - Neobsahuje
	 * 5 - Znížená 2
	 *
	 * Pre GET platí, že vracia reťazec:
	 * Do 31.12.2024:
	 * "20" - Základná
	 * "10" - Znížená
	 * "0"  - Nulová
	 * "Neobsahuje" - Neobsahuje
	 *
	 * Od 1.1.2025:
	 * "23" - Základná
	 * "19" - Znížená
	 * "5" - Znížená 2
	 * "0"  - Nulová
	 * "Neobsahuje" - Neobsahuje
	 */
	VatRate?: string;
	/**
	 * Id hlavnej skupiny
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	Id_Stock_Items_Group_Default?: number;
	/**
	 * Typ skladovej karty.
	 * 1 - Skladová karta
	 * 2 - Služba
	 * 6 - Zariadenie
	 */
	Type: "1" | "2" | "6";
	/**
	 * Alternatívy skladovej karty
	 * @readonly
	 */
	StockItemAlternatives?: DtoStockItemAndServiceAlternative[];
	/** Typ produktového kódu */
	Product_Code_Type?: string;
	/** Sadzba spotrebnej dane */
	Alcohol_Excise_Tax?: number;
	/** Objem HMJ */
	Alcohol_Volume?: number;
	/** Obsah alkoholu */
	Alcohol_Percent?: number;
	/**
	 * Prenos daňovej povinnosti
	 * 1 - Zapnutý
	 * 2 - Vypnutý
	 */
	Transfer_Of_Tax_Liability?: number;
	/** Poznámka */
	Description?: string;
	/** Hlavný sklad (zadáva sa kód skladu z číselníka skladov) */
	Default_Stock?: string;
	/** Intrastat – krajina pôvodu (skratka podľa predpisu štatistického úradu) */
	Ist_Country_Code?: string;
	/** Partner pre zariadenie – číslo partnera */
	Partner_Ns_Number?: string;
	/** Umiestnenie zariadenia */
	Location_Device?: string;
	/** Výrobné číslo zariadenia */
	Serial_Number_Device?: string;
	/**
	 * Používanie výrobných čísel na karte
	 * 1 - Zapnuté
	 * 2 - Vypnuté
	 */
	UseSerialNumber?: number;
	/** `CustomColumns`. */
	CustomColumns?: CustomField[];
}

/** DTO trieda pre sklad. */
export interface DtoStocks {
	/**
	 * ID záznamu
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 */
	IdRecord?: number;
	/** Názov skladu. */
	Name?: string;
	/** Kód skladu. */
	Code?: string;
	/** EAN skladu. */
	Stock_Ean?: string;
	/**
	 * História - dátum zmeny skladu.
	 * @format date-time (ISO 8601 string)
	 */
	Date_Changed?: string;
	/**
	 * Typ skladu.
	 * 0 - Nedefinovaný,
	 * 1 - Tovarový,
	 * 2 - Materiálový,
	 * 3 - Dopravný,
	 * 4 - Colný,
	 * 5 - Konsignačný,
	 * 6 - Skupina skladov.
	 */
	Stock_Type?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
	/**
	 * Spôsob (legislatívneho) oceňovania skladových zásob.
	 * 0 - Nedefinovaný,
	 * 1 - Vážený aritmetický priemer,
	 * 2 - FIFO.
	 */
	Valuation_Type?: 0 | 1 | 2;
	/**
	 * Aktívnosť skladu.
	 * -1 - Neaktívny,
	 * 0 - Aktívny.
	 */
	Inactive?: number;
}

/** Onix `Message` DTO (generated from docs/V1.json). */
export interface Message {
	/**
	 * Pomocné id importovaného záznamu.
	 * @readonly
	 */
	RecordExternalIdentificator?: string;
	/**
	 * Text.
	 * @readonly
	 */
	Message?: string;
}

/** Onix `Result` DTO (generated from docs/V1.json). */
export interface Result {
	/**
	 * Pomocné id importovaného záznamu.
	 * @readonly
	 */
	RecordExternalIdentificator?: string;
	/**
	 * Id uloženého záznamu.
	 * @format int64 (may exceed JS Number.MAX_SAFE_INTEGER)
	 * @readonly
	 */
	IdRecord?: number;
	/**
	 * Výsledok pridania záznamu
	 * 0 - Záznam bol pridaný
	 * 1 - Záznam bol pridaný s warningami
	 * 2 - Záznam bol pridaný s errormi
	 * 3 - Záznam nebol pridaný
	 * @readonly
	 */
	Result?: 0 | 1 | 2 | 3;
	/**
	 * Zoznam chýb, kvôli ktorým sa nepodarilo uložiť/vymazať.
	 * @readonly
	 */
	Errors?: Message[];
	/**
	 * Zoznam upozornení.
	 * Ak sa nepodarilo uložiť/vymazať, bude vždy prázdne.
	 * @readonly
	 */
	Warnings?: Message[];
}

// NOTE: 3 `PagedResult_*` definition(s) intentionally not generated —
// use the generic `PagedResult<T>` from ./types.ts instead.
